apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: monitoring
  labels:
    helm.sh/chart: kiali-server-1.72.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v1.72.0"
    app.kubernetes.io/version: "v1.72.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"